repos:
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        args: ["-l", "80", "-t", "py37"]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: debug-statements
-   repo: https://github.com/PyCQA/flake8
    rev: '6.1.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        exclude: ^notebooks
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.7.1'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        exclude: docs/conf.py
        additional_dependencies:
        -   types-python-dateutil
        -   types-PyYAML
-   repo: https://github.com/codespell-project/codespell
    rev: 'v2.2.6'
    hooks:
    -   id: codespell
        args: ["-I", "codespell.txt"]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        args: ["--py36-plus"]

ci:
    autoupdate_schedule: monthly
